name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: '🐛 '
labels: ['bug']

body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      multiple: true
      options:
        - '@nestjs-redis/kit'
        - '@nestjs-redis/client'
        - '@nestjs-redis/lock'
        - '@nestjs-redis/throttler-storage'
        - '@nestjs-redis/health-indicator'
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: '0.10.0'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Brief description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Install package
        2. Configure module
        3. Run code
        4. See error
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code example
      placeholder: Minimal code that reproduces the issue
      render: typescript

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        Node.js: 18.x
        NestJS: 10.x
        Redis: 7.x
      value: |
        Node.js: 
        NestJS: 
        Redis:
