blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/CSenshi/nestjs-redis/discussions
    about: Ask questions and discuss ideas
  - name: 📖 Documentation
    url: https://github.com/CSenshi/nestjs-redis#readme
    about: Check the documentation first
