name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  main:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:8-alpine
        ports: ['6379:6379']

      redis-cluster:
        image: grokzen/redis-cluster:7.0.10
        ports: ['7010-7015:7010-7015']
        env:
          IP: 0.0.0.0
          INITIAL_PORT: 7010

    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v5
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test
      - run: pnpm build
      - run: pnpm build:example
      - run: pnpm format:check
